// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szlkizzsnrjjpibsjizn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6bGtpenpzbnJqanBpYnNqaXpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzODc4MTgsImV4cCI6MjA4Mzk2MzgxOH0.owbx7K0YVRE2xhNaJTlrS_uCrLCOesIIyBghroY8shs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
